name: 'Publish'

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Login to ghcr.io
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      uses: home-assistant/builder@2023.06.1
      with:
        args: |
          --${{ matrix.arch }} \
          --target mariadb \
          --cosign \
          --no-cache \
          --docker-hub ghcr.io/${{ github.actor }}
