name: 'Publish'

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.4.0
    - name: Login to DockerHub
      uses: docker/login-action@v1.14.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish
      uses: home-assistant/builder@2022.01.0
      with:
        args: |
          --all \
          --target mariadb \
          --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
